name: Python Playwright Tests

on:
 push:
   branches: [ "main" ]
 pull_request:
  branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt

      - name: Install Playwright browsers
        run: |
         python -m playwright install --with-deps

      - name: Run pytest and generate HTML report
        run: |
         mkdir -p reports
         pytest -v --html=reports/report.html --self-contained-html

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v3
        with:
         name: pytest-report
         path: reports/report.html